export enum Routes {
  Login = "/login",
  Dashboard = "/dashboard",
  Notification = "/notification",
  Attendance = "/attendance",
  AddAttendance = "/attendance/add",
  EditAttendance = "/attendance/edit/id",
  MarkAttendance = "/mark-attendance",
  Fund = "/fund",
  Member = "/members",
  AddMember = "/members/add",
  ShiftIncharge = "/shift-incharge",
  MissingShoes = "/missing-shoes",
  AddMissingShoes = "/add-missing-shoes",
  LeaveRequest = "/leaves",
  AddLeaveRequest = "/leaves/add",
}