export enum Routes {
  Login = "/login",
  Dashboard = "/dashboard",
  Notification = "/notification",
  Attendance = "/attendance",
  AddAttendance = "/attendance/add",
  EditAttendance = "/attendance/edit",
  MarkAttendance = "/attendance/mark",
  Fund = "/fund",
  Members = "/members",
  AddMember = "/members/add",
  EditMember = "/members/edit",
  MemberDetails = "/members/details",
  ShiftIncharge = "/shift-incharge",
  MissingShoes = "/missing-shoes",
  AddMissingShoes = "/add-missing-shoes",
  LeaveRequest = "/leaves",
  AddLeaveRequest = "/leaves/add",
  Playground = "/playground",
  EditLeaveRequest = "/leaves/edit",
  AttendanceReport = "/attendance-report",
}
