
#build
name: Check
on:
  pull_request:
    branches:
      - main
jobs:

 build:
    name: Check
    runs-on: ubuntu-latest

    steps:
       	- name: Run template check
          uses: Frenetz/check-debug-statements@main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            