name: Console

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Console
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run template check
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "console.log"
          run: exit 1

      - name: Run tests
        run: npm test
