name: check-debug-statements

on: pull_request
jobs:
  check-debug-statements:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Simple NPM package by FireWork Production Private Ltd.
        uses: FireWork-Production-Private-Ltd/npm-package-registery@v2.0.0

      - name: Run template check
        uses: Frenetz/check-debug-statements@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
